# Generated by Django 5.2 on 2025-04-29 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_alter_teachingassignment_teacher'),
        ('communication', '0002_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_channels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channel',
            name='groups_allowed',
            field=models.ManyToManyField(blank=True, related_name='channels', to='adminpanel.group'),
        ),
        migrations.AddField(
            model_name='channel',
            name='max_participants',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='channel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
