# Generated by Django 5.2 on 2025-05-06 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_notification_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='uploaded_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='communication.uploadedfile'),
        ),
    ]
