# Generated by Django 5.2 on 2025-05-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0007_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='is_muted_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stream',
            name='is_speaking',
            field=models.BooleanField(default=False),
        ),
    ]
