# Generated by Django 5.2 on 2025-06-09 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0008_stream_is_muted_by_admin_stream_is_speaking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='image',
            field=models.URLField(max_length=2048),
        ),
    ]
